// generated by stringer -type=Languages; DO NOT EDIT

package main

import "fmt"

const _Languages_name = "IrishGaelicWelsh"

var _Languages_index = [...]uint8{0, 5, 11, 16}

func (i Languages) String() string {
	if i < 0 || i+1 >= Languages(len(_Languages_index)) {
		return fmt.Sprintf("Languages(%d)", i)
	}
	return _Languages_name[_Languages_index[i]:_Languages_index[i+1]]
}
